CREATE TABLE clients (id serial, name varchar(100) not null, phone varchar(100) not null);

insert into clients (name, phone) values ('Anna', '11-11-11'), ('Kate', '22-22-22'), ('Max', '33-33-33')
--
-- INSERT INTO products (title, price) VALUES ('Bread', 40), ('Milk', 80);
--
-- CREATE TABLE users (
--     username VARCHAR(50) NOT NULL,
--     password VARCHAR(100) NOT NULL,
--     enabled boolean NOT NULL,
--     PRIMARY KEY (username)
-- );
--
-- INSERT INTO users
-- VALUES
-- ('user1', '{noop}123', true),
-- ('user2', '{noop}123', true);
--
-- CREATE TABLE authorities (
--     username varchar(50) NOT NULL,
--     authority varchar(50) NOT NULL,
--
--     CONSTRAINT authorities_idx UNIQUE (username, authority),
--
--     CONSTRAINT authorities_ibfk_1
--     FOREIGN KEY (username)
--     REFERENCES users (username)
-- );
--
-- INSERT INTO authorities
-- VALUES
-- ('user1', 'ROLE_ADMIN'),
-- ('user1', 'ROLE_USER'),
-- ('user2', 'ROLE_USER');